# Generated by Django 5.1.2 on 2024-10-23 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=200)),
                ('isbn_number', models.IntegerField()),
                ('book_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact_no', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_id', models.CharField(max_length=200)),
                ('reader_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact_no', models.IntegerField()),
                ('address', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('date_borrowed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_borrowed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='libapp.book')),
            ],
        ),
    ]
