# Generated by Django 5.1.2 on 2024-10-30 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0002_reader_return_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Librarian',
        ),
    ]
