# Generated by Django 5.1.2 on 2024-10-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0003_delete_librarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_img',
            field=models.ImageField(default='', upload_to='libapp/photos'),
        ),
    ]
