# Generated by Django 5.1.2 on 2024-10-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0004_book_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.ImageField(default='', upload_to='photos/'),
        ),
    ]
